site_name: Wave wet en regelgeving

theme:
  name: material
  langueage: nl
 
# Copyright
copyright: Copyright © 2023 - 2024 Wave Testserver

  favicon: img/logoTedeapolis.png
  logo: img/logoTedeapolis.webp

nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Wetboek: wetboek.md
